# Generated by Django 5.2.4 on 2025-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='categories',
            field=models.ManyToManyField(related_name='category_preferences', to='news.category'),
        ),
    ]
